buildscript {
    ext {
        compose_version = '1.10.6'
        kotlin_version = '2.3.20'
    }
    repositories {
        google()
        mavenCentral()
    }
}

plugins {
    alias libs.plugins.android.application apply false
    alias libs.plugins.android.library apply false
    alias libs.plugins.jetbrains.kotlin.android apply false
    alias libs.plugins.google.dagger.hilt.android apply false
    alias libs.plugins.google.devtools.ksp apply false
    alias libs.plugins.compose.compiler apply false
    alias libs.plugins.google.android.gms.oss.licenses.plugin apply false
}