package dev.msartore.ares.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF196e00)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF9ff87f)
val md_theme_light_onPrimaryContainer = Color(0xFF012200)
val md_theme_light_secondary = Color(0xFF54624d)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFd7e7cb)
val md_theme_light_onSecondaryContainer = Color(0xFF131f0e)
val md_theme_light_tertiary = Color(0xFF386667)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFbcebed)
val md_theme_light_onTertiaryContainer = Color(0xFF002022)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfdfdf6)
val md_theme_light_onBackground = Color(0xFF1a1c18)
val md_theme_light_surface = Color(0xFFfdfdf6)
val md_theme_light_onSurface = Color(0xFF1a1c18)
val md_theme_light_surfaceVariant = Color(0xFFdfe4d7)
val md_theme_light_onSurfaceVariant = Color(0xFF43483f)
val md_theme_light_outline = Color(0xFF73796d)
val md_theme_light_inverseOnSurface = Color(0xFFf1f1ea)
val md_theme_light_inverseSurface = Color(0xFF2f312d)

val md_theme_dark_primary = Color(0xFF84db66)
val md_theme_dark_onPrimary = Color(0xFF043900)
val md_theme_dark_primaryContainer = Color(0xFF0b5300)
val md_theme_dark_onPrimaryContainer = Color(0xFF9ff87f)
val md_theme_dark_secondary = Color(0xFFbccbb1)
val md_theme_dark_onSecondary = Color(0xFF273421)
val md_theme_dark_secondaryContainer = Color(0xFF3d4b36)
val md_theme_dark_onSecondaryContainer = Color(0xFFd7e7cb)
val md_theme_dark_tertiary = Color(0xFFa0cfd1)
val md_theme_dark_onTertiary = Color(0xFF003739)
val md_theme_dark_tertiaryContainer = Color(0xFF1e4e50)
val md_theme_dark_onTertiaryContainer = Color(0xFFbcebed)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1a1c18)
val md_theme_dark_onBackground = Color(0xFFe2e3dc)
val md_theme_dark_surface = Color(0xFF1a1c18)
val md_theme_dark_onSurface = Color(0xFFe2e3dc)
val md_theme_dark_surfaceVariant = Color(0xFF43483f)
val md_theme_dark_onSurfaceVariant = Color(0xFFc3c8bc)
val md_theme_dark_outline = Color(0xFF8d9287)
val md_theme_dark_inverseOnSurface = Color(0xFF1a1c18)
val md_theme_dark_inverseSurface = Color(0xFFe2e3dc)