plugins {
    alias libs.plugins.android.application
    alias libs.plugins.jetbrains.kotlin.android
    alias libs.plugins.google.android.gms.oss.licenses.plugin
    alias libs.plugins.google.dagger.hilt.android
    alias libs.plugins.google.devtools.ksp
    alias libs.plugins.compose.compiler
}

def keystorePropertiesFile = rootProject.file("./keystore.properties")
def keystoreProperties = new Properties()

if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    namespace 'dev.msartore.ares'
    
    defaultConfig {
        applicationId "dev.msartore.ares"
        minSdk 26
        targetSdk 35
        compileSdk 36
        versionCode 36
        versionName "0.0.33"
        resourceConfigurations += ['en', 'it']
        vectorDrawables.useSupportLibrary = true

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        vectorDrawables {
            useSupportLibrary true
        }
    }
    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        debug {
            applicationIdSuffix ".debug"
            versionNameSuffix "-debug"
            debuggable true
        }
        release {
            debuggable false
            minifyEnabled true
            multiDexEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
        freeCompilerArgs += [
                "-opt-in=kotlin.RequiresOptIn"
        ]
    }
    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1,INDEX.LIST,io.netty.versions.properties}'
        }
    }
    dependenciesInfo {
        includeInBundle true
    }
}

dependencies {
    // Hilt
    implementation libs.hilt.android
    ksp libs.hilt.compiler

    // Hilt + Compose Navigation integration
    implementation libs.hilt.navigation.compose

    implementation libs.core.ktx

    // Guava (needed by CameraX ListenableFuture)
    implementation libs.guava

    // Accompanist
    implementation libs.accompanist.systemuicontroller
    implementation libs.accompanist.appcompat.theme
    implementation libs.accompanist.swiperefresh
    implementation libs.accompanist.permissions

    // Ktor
    implementation libs.ktor.server.core
    implementation libs.ktor.server.jetty
    implementation libs.ktor.server.html.builder
    implementation libs.ktor.server.auto.head.response
    implementation libs.ktor.client.core
    implementation libs.ktor.client.cio

    // Preferences DataStore
    implementation libs.datastore.preferences

    // Gson
    implementation libs.gson

    // Zxing
    implementation libs.core
    implementation libs.javase

    // MLKit Barcode
    implementation libs.barcode.scanning

    // CameraX libraries
    implementation libs.camera.core
    implementation libs.camera.camera2
    implementation libs.camera.lifecycle
    implementation libs.camera.view

    // Open source notices  libraries
    implementation libs.play.services.oss.licenses

    // Material theme
    implementation libs.material

    implementation libs.lifecycle.viewmodel.compose
    implementation libs.lifecycle.runtime.ktx
    implementation libs.activity.compose
    implementation libs.ui
    implementation libs.ui.tooling.preview
    implementation libs.material3
    implementation libs.material3.adaptive.navigation.suite

    testImplementation libs.junit

    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ui.test.junit4

    debugImplementation libs.ui.tooling
    debugImplementation libs.ui.test.manifest
}